### PR TITLE
Build FNA with Media Foundation backend.

### PR DESCRIPTION
**Pull request by rbernon**
This is the wine-mono side of things for https://github.com/madewokherd/FNA/pull/4

### CODE REVIEW

**Comment by madewokherd** [comment]
Hi, why are we making this separately configurable, unlike the other FNA helper libraries, while also putting the build code in fna.make, unlike the other FNA libraries?

**Comment by rbernon** [comment]
No reason of course I'll change that.

**Comment by madewokherd** [comment]
BTW, if you update the submodule ref in your PR, it should allow the CI to work. I can handle any complexity it adds to merging.

**Comment by madewokherd** [comment]
Most of it is in the FNA submodule, but this part looks good, and it even passed CI somehow. That never happens to me.

**Comment by madewokherd** [comment]
From the CI process:
```
2021-08-03T16:14:19.5085744Z Starting test: x86.xnatest
2021-08-03T16:14:19.6122842Z 0360:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
2021-08-03T16:14:19.8555650Z 0360:fixme:service:I_ScRegisterDeviceNotification Notification filters are not yet implemented.
2021-08-03T16:14:19.8834639Z 0360:err:wgl:init_opengl Failed to load libGL: libGL.so.1: cannot open shared object file: No such file or directory
2021-08-03T16:14:19.8836113Z 0360:err:wgl:init_opengl OpenGL support is disabled.
2021-08-03T16:14:19.8947325Z 0360:fixme:win:RegisterTouchWindow (0007004A 00000003): stub
2021-08-03T16:14:20.0415290Z exception inside UnhandledException handler: (null) assembly:C:\windows\mono\mono-2.0\lib\mono\4.5\mscorlib.dll type:NullReferenceException member:(null)
2021-08-03T16:14:20.0416868Z 
2021-08-03T16:14:20.0577544Z [ERROR] FATAL UNHANDLED EXCEPTION: Microsoft.Xna.Framework.Graphics.NoSuitableGraphicsDeviceException: Invalid window
2021-08-03T16:14:20.0580299Z   at Microsoft.Xna.Framework.SDL2_FNAPlatform.CreateWindow () [0x0016e] in <257ae10c02534a07860d9115c5698c61>:0 
2021-08-03T16:14:20.0581954Z   at Microsoft.Xna.Framework.Game..ctor () [0x000f1] in <257ae10c02534a07860d9115c5698c61>:0 
2021-08-03T16:14:20.0583313Z   at TestGame..ctor () [0x00000] in <8ff6cedc8ec04303a8c019c16676cffe>:0 
2021-08-03T16:14:20.0813252Z Test failed(1): x86.xnatest
```

It's not clear to me why your change would've caused this failure, but since it's new to me and in the changed component I have to assume it's related.

**Comment by madewokherd** [comment]
That error has now appeared on another unrelated CI run, so it seems it's not related to your patch.

**Comment by rbernon** [comment]
Okay, from the error I looks like it's caused by some missing OpenGL support on the CI but that may be something else.

**Comment by madewokherd** [comment]
Yeah, I'm not sure what changed though. I'm hoping https://github.com/madewokherd/wine-mono/pull/110 will clear it up. Either way, you don't need to worry about it.

**Comment by madewokherd** [comment]
Merged manually.

**Pull request closed without merging**
