### PR TITLE
msi: Add registry entries for XNA 4.0.

### PR DESCRIPTION
**Pull request by cdavis5e**

### CODE REVIEW

**Comment by madewokherd** [comment]
Why do we want to prevent XNA4 from installing?

**Comment by cdavis5e** [comment]
> Why do we want to prevent XNA4 from installing?

We don't necessarily, but if these entries aren't present, some XNA programs refuse to start. See, for example, [here](https://github.com/CnCNet/dta-mg-client-launcher/blob/794550a6f24f4ae13e37d67b1dd09ba49987b47d/Program.cs#L234).

**Comment by madewokherd** [comment]
I'm not sure about this. Installing XNA may still be useful in some situations (especially if we can fix the core libraries, but I think some of the others work now), and I don't want to risk interfering with that. I also like that you can install .NET Framework later and have things still work. Presumably, the requirement to install the redist also exists on Windows.

**Comment by cdavis5e** [comment]
All right. Maybe when FNA is further along and we won't need to install the runtime anymore, then we can do this.

**Comment by madewokherd** [comment]
I ended up looking into this a bit more due to a Proton issue, and it seems that all the libraries we might use from the XNA redist rely on XNA internals, so the XNA developers really didn't believe in dll separation, and it's all-or-nothing for these libraries. I remember trying it, but it probably only seemed to work because the program wasn't really using those libraries, or it failed somewhere else before it could. I still think we should be able to fix Wine Mono so the XNA redist can work, but even then I wouldn't want to make it the default, so making it a little more complicated to set up seems fine.

The case of installing a game that auto-installs XNA, before installing .NET Framework, is also a corner case where I think it's acceptable to have to run the XNA installer.

So maybe we should do this after all.

**Comment by madewokherd** [comment]
An interesting side note: There never was a 64-bit XNA redist, but this still adds registry keys for one. On 64-bit Windows, running an architecture-independent .exe that depends on XNA works, somehow, even though there are no 64-bit libraries. We have a test for this, which I expected to fail. I think they must be detecting the dependency and running it as 32-bit. 

I haven't seen this break anything yet, and since we may end up running XNA programs in 64-bit processes, it makes sense to have the registry keys for it too. And it really doesn't have much to do with your patch, if that's going to break things it'll happen for other reasons. But the potential for running Windows XNA games in 64-bit may cause problems someday.

**Comment by madewokherd** [comment]
I tried running the xna4 installer with this patch, and it still installs, which is fine. Skipping the install would've also been fine, but I wanted to make sure it wouldn't report an error or something.

**Pull request merged**
